### ISSUE TITLE
Intermittent android.runtime.JavaProxyThrowable: Realms.RealmException: Data type mismatch

### ISSUE THREAD

**Issue by hrach** [realm/realm-dotnet#1193]
I'm getting intermittent exception, which I can replicate, sadly, I'm unable to debug it. Anytime I breakpoint in the code to realize, what is causing it, it works ok.

<details>
 <summary>This is my stack trace:</summary>

```
Xamarin caused by: android.runtime.JavaProxyThrowable: Realms.RealmException: Data type mismatch
  at Realms.NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider) [0x00014] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.QueryHandle.NullEqual (System.IntPtr columnIndex) [0x00009] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResultsVisitor.AddQueryEqual (Realms.QueryHandle queryHandle, System.String columnName, System.Object value) [0x0000e] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression b) [0x00183] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000d2] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResultsVisitor.VisitCombination (System.Linq.Expressions.BinaryExpression b, System.Action`1[T] combineWith) [0x00012] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResultsVisitor.VisitBinary (System.Linq.Expressions.BinaryExpression b) [0x0000c] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000d2] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResultsVisitor.VisitMethodCall (System.Linq.Expressions.MethodCallExpression m) [0x0008b] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.ExpressionVisitor.Visit (System.Linq.Expressions.Expression exp) [0x000ec] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at Realms.RealmResults`1[T].CreateHandle () [0x00042] in <03f96af2858c46cfb7cbbc741b866d11>:0 
  at System.Lazy`1[T].CreateValue () [0x00075] in <20a7a65eda8a4c68a2c01bd211488791>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at TickinCzHost.Services.SyncService+<>c__DisplayClass6_0+<<SyncTicketsAsync>b__0>d.MoveNext () [0x00070] in <44ba0cf02eeb416c99548bec8852905f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at TickinCzHost.Services.SyncService+<SyncTicketsAsync>d__6.MoveNext () [0x00082] in <44ba0cf02eeb416c99548bec8852905f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at TickinCzHost.ViewModel.EventOverviewViewModel+<SynchronizeTicketsAsync>d__4.MoveNext () [0x00070] in <44ba0cf02eeb416c99548bec8852905f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at TickinCzHost.Droid.UI.InternetConnectionExceptionHandler.CheckConnectionAndShowInfo (System.Exception e, Android.Content.Context context) [0x0002b] in <8848aa6f093d4a8083a848a67a1b77af>:0 
  at TickinCzHost.Droid.Fragments.EventOverviewFragment+<>c__DisplayClass8_0+<<OnCreateView>b__0>d.MoveNext () [0x000c4] in <8848aa6f093d4a8083a848a67a1b77af>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <20a7a65eda8a4c68a2c01bd211488791>:0 
  at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <b7629c3333c24a39a5eae42b47c6aca8>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <b7629c3333c24a39a5eae42b47c6aca8>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <b7629c3333c24a39a5eae42b47c6aca8>:0 
  at (wrapper dynamic-method) System.Object:a2139cff-41f9-4ded-b837-5c8b561581b2 (intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:168)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```
</details>

It could be somehow related to #1192.

**Comment by fealebenpae** [comment]
Could you please post the LINQ query you use, and the class that defines your model?

**Comment by hrach** [comment]
It seems it's caused by this:

```cs
var tickinEvent = realm.Find<EventEntity>(eventId);
var toSync = realm.All<TicketEntity>().Where(t => t.Event == tickinEvent && t.PendingSync == true);

public class EventEntity : RealmObject
{
	[PrimaryKey]
	public int Id { get; set; }
	// unrelated properties skipped
}
public class TicketEntity : RealmObject
{
	[PrimaryKey]
	public int Id { get; set; }
	public bool PendingSync { get; set; }
	public EventEntity Event { get; set; }
	// unrelated properties skipped
}
```
Still hodls, that I'm unable to replicate it, if I set a breakpoint.

**Comment by hrach** [comment]
Got it! Its probably because the tickinEvent is null! But I have no idea why the sync between thread so much sucks. I have an main activity, which do sync of events (in non-ui thread). After events sync list view on main event is refreshed, I click on the event, new activity opened and reads the event and sets new activity's title. I click the sync button and it in another thread fails with this code. This is very concerning :|

I always use WriteAsync so I excpet that all threads in later event cycles will have correct state of the store.

**Comment by hrach** [comment]
I understand that my last comments is more a question into the forum, but **current expcetion may be enhanced by more info - which datatypes are mismatched, etc**.

Still, if somebody would point be to righe place where to ask or answered how actually the multi-thread sync works :-O I still can't beleive that in another activy after List redraw I can finish in such state.

**Comment by nirinchev** [comment]
@hrach sorry for following up so slowly - we have forums now - https://forums.realm.io - so feel free to post there :) We've made improvements on `WriteAsync` so you shouldn't be experiencing issues anymore. If you do, please reopen the issue.
