### ISSUE TITLE
Accessing Removed object from ChangeNotification listener results in AccessViolationException

### ISSUE THREAD

**Issue by Shaddix** [realm/realm-dotnet#1286]
I'm listening to the Change notifications on a certain collection. Then I create and remove object from Realm.
Create notifications works ok, Remove notification is called, but whenever I try to access any property (e.g. `Id` in the example) AccessViolationException is thrown.

Is it as designed? Is there any way I can determine what object was deleted?

Here's the code snippet (using the 1.1.1 version from Nuget on Windows 32 bit):
```
        public class Tst1 : RealmObject
        {
            [PrimaryKey]
            public string Id { get; set; }
        }
        private void Form1_Load(object sender, EventArgs e)
        {
            var config = new RealmConfiguration(Path.GetTempFileName())
            {
            };
            var realm = Realm.GetInstance(config);
            realm.All<Tst1>().SubscribeForNotifications(Changed);

            var r = Realm.GetInstance(config);
            var tst1 = new Tst1()
            {
                Id = "1"
            };
            r.Write(() =>
            {
                r.Add(tst1);
            });
            realm.Refresh();

            r.Write(() =>
            {
                r.Remove(tst1);
            });
            realm.Refresh();
        }


        private void Changed(IRealmCollection<Tst1> sender, ChangeSet changes, Exception error)
        {
            if (changes == null)
                return;

            foreach (int changesDeletedIndex in changes.DeletedIndices)
            {
                var z = sender[changesDeletedIndex];
                Console.WriteLine(z.Id); //here goes the AccessViolationException
            }
        }
```

**Comment by nirinchev** [comment]
Can you post the exception object?

**Comment by Shaddix** [comment]
You mean the stacktrace?
The message is: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."
```
   at Realms.ObjectHandle.NativeMethods.get_string(ObjectHandle handle, IntPtr propertyIndex, IntPtr buffer, IntPtr bufsize, Boolean& isNull, NativeException& ex)
   at Realms.ObjectHandle.<>c__DisplayClass13_0.<GetString>b__0(IntPtr buffer, IntPtr length, Boolean& isNull, NativeException& ex) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Handles\ObjectHandle.cs:line 284
   at Realms.MarshalHelpers.GetString(NativeStringGetter getter) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\MarshalHelpers.cs:line 116
   at Realms.ObjectHandle.GetString(IntPtr propertyIndex) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Handles\ObjectHandle.cs:line 284
   at Realms.RealmObject.GetStringValue(String propertyName) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\RealmObject.cs:line 153
   at RealmWin.Form1.Tst1.get_Id() in C:\DiskD\Projects\RealmWin\RealmWin\Form1.cs:line 25
   at RealmWin.Form1.Changed(IRealmCollection`1 sender, ChangeSet changes, Exception error) in C:\DiskD\Projects\RealmWin\RealmWin\Form1.cs:line 68
   at Realms.RealmCollectionBase`1.Realms.RealmCollectionNativeHelper.Interface.NotifyCallbacks(Nullable`1 changes, Nullable`1 exception) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\RealmCollectionBase.cs:line 319
   at Realms.RealmCollectionNativeHelper.NotificationCallbackImpl(IntPtr managedResultsHandle, IntPtr changes, IntPtr exception) in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Linq\RealmCollectionNativeHelper.cs:line 38
   at Realms.SharedRealmHandle.NativeMethods.refresh(SharedRealmHandle sharedRealm, NativeException& ex)
   at Realms.SharedRealmHandle.Refresh() in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Handles\SharedRealmHandle.cs:line 184
   at Realms.Realm.Refresh() in C:\jenkins\workspace\_realm-dotnet_release_1.1.1-S7NL3AZZ3PXAXXTBAUXPTN4JUF4H2MQM3SW4U2P73STDAAHWRYIA\Shared\Realm.Shared\Realm.cs:line 762
   at RealmWin.Form1.Form1_Load(Object sender, EventArgs e) in C:\DiskD\Projects\RealmWin\RealmWin\Form1.cs:line 56
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by nirinchev** [comment]
Getting a deleted item is indeed an unsupported scenario. The `DeletedIndices` collection contains the indices of the items prior to deletion, so those will be incorrect for the current state of the collection. For example, if you have 3 items: `{ A, B, C }` and delete `B`, its index would be `1`, but in the current state: `{ A, C }`, that would correspond to `C`'s index. If you need to do something with `B`, you should do it prior to its deletion. `DeletedIndices` is intended to be used just for updating the UI, e.g. when manually updating a `UITableView` on iOS.

The reason you see this exception is the result of another bug where instead of throwing `ArgumentOutOfRangeException`, we return an invalid object when the index is out of range. In your case, you're trying to get the object at index `0` of an empty collection. I've submitted a PR that will correct that behavior and make it clearer what's going on.

**Comment by Shaddix** [comment]
Thanks a lot for the explanation

**Comment by Shaddix** [comment]
Could be closed then
