### ISSUE TITLE
Migration Crash

### ISSUE THREAD

**Issue by eyadon** [realm/realm-dotnet#1325]
I am getting some crash reports related to migration, stack trace below.
Have not seen this on debug builds, only production installs for a few users in the field...
Android only, Realm 1.0.3, various versions of our app (so not all the same migration, we think)

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.AggregateException: Exception occurred in a Realm migration callback. See inner exception for more details. ---> 

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform member binding on `null' value
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
  at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0) [0x00127] in <e82497268f274b128bb199c0fc713894>:0 
  at RealmDAL.RealmFactory+<>c.<GetConfiguration>b__0_4 (Realms.Migration migration, System.UInt64 oldSchemaVersion) [0x00518] in <0d83161291f64dc8afd283d17827e4c1>:0 
  at Realms.Migration.Execute (Realms.Realm oldRealm, Realms.Realm newRealm) [0x00025] in <47e690a032c24420b246c219c61e5113>:0 
   --- End of inner exception stack trace ---
  at Realms.RealmConfiguration.CreateRealm (Realms.Schema.RealmSchema schema) [0x00097] in <47e690a032c24420b246c219c61e5113>:0 
  at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config, Realms.Schema.RealmSchema schema) [0x0003b] in <47e690a032c24420b246c219c61e5113>:0 
  at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x0000d] in <47e690a032c24420b246c219c61e5113>:0 
  at RealmDAL.RealmRepositoryHelper.ForceMigration () [0x0008d] in <0d83161291f64dc8afd283d17827e4c1>:0 
  at VesselViewMobile.App..ctor () [0x0000c] in <9d9294bcd09f424c85a4f62727aa9b55>:0 
  at VesselViewMobile.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x000c4] in <59e1417966434d548bd952b6d58efb97>:0 
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <f9ea314dc48f4cf0bf0fd7930113561a>:0 
  at (wrapper dynamic-method) System.Object:cd6f0927-0f7d-4fb8-aaa8-2ce8beff70ba (intptr,intptr,intptr)
---> (Inner Exception #0) Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform member binding on `null' value
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
  at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0) [0x00127] in <e82497268f274b128bb199c0fc713894>:0 
  at RealmDAL.RealmFactory+<>c.<GetConfiguration>b__0_4 (Realms.Migration migration, System.UInt64 oldSchemaVersion) [0x00518] in <0d83161291f64dc8afd283d17827e4c1>:0 
  at Realms.Migration.Execute (Realms.Realm oldRealm, Realms.Realm newRealm) [0x00025] in <47e690a032c24420b246c219c61e5113>:0 <---

	at md526cbf5a040db3ba335ee9655fe09341d.MainActivity.n_onCreate(Native Method)
	at md526cbf5a040db3ba335ee9655fe09341d.MainActivity.onCreate(MainActivity.java:34)
	at android.app.Activity.performCreate(Activity.java:6705)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6217)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by istx25** [comment]
Hi @eyadon. Thanks for reaching out about this. Would you be able to provide us with a code sample on how you're doing migrations? It's possible there's an error in there that's causing: `Cannot perform member binding on `null' value`. Looking forward to hearing from you.

**Comment by fealebenpae** [comment]
Hey @eyadon,

Looking at the exception it seems that some piece of code is trying to perform a dynamic operation on a null value.
```csharp
dynamic foo = null;
foo.Bar;
```
crashes similarly. Like @istx25 said, you can share a code sample, or try to audit your code for where a `dynamic` value might be null.

**Comment by eyadon** [comment]
D'oh.
I looked into this a while back (when it was just one person crashing) and for some reason got hung up on one of our classes being missing?  I think I saw an example of that exception involving foo.GetType() and went the wrong direction.
Thanks for the suggestion; our migration code is pretty extensive.

**Comment by istx25** [comment]
Great to hear. Let us know if you have any other questions. :)
