### ISSUE TITLE
Deleting first item in RecyclerView throws java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by StephenBeirlaen** [realm/realm-dotnet#1384]
## Goals

I am using Realm Mobile Platform. I am building an app that shows products from a realm in a RecyclerView, synchronized with the object server. My RecyclerView adapter is based on the [Android example](https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java). I can add and remove items from the list. Inserting items is working without problems. Deleting is working as well, but not when I want to delete the first item.

Inside CreateListener, when my app receives the delete notification, I have verified what's being passed to NotifyItemRangeRemoved (index 0, which looks right?). Somewhere after this call, the app crashes.

I am not sure if this is an issue with Realm or with the RecyclerView. But I thought it was better to ask this question here as you might have experience with both. I have searched for solutions for the exception below and found that I should do all Realm data access on the main thread for the RecyclerView to work [source](http://stackoverflow.com/questions/31759171/recyclerview-and-java-lang-indexoutofboundsexception-inconsistency-detected-in). So it might be me using Realm incorrectly. But I believe I am already doing everything on the UI thread (except logging in).

## Expected Results

The delete notifications should remove all items from the RecyclerView without problems.

## Actual Results

```
05-07 10:46:36.540 7181-7181/RealmShopDemo.Droid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: RealmShopDemo.Droid, PID: 7181
                                                                   java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:4
                                                                       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:605)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                       at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
                                                                       at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

## Steps to Reproduce

Install the app, log-in with the correct Realm credentials for your object server, and click get products.
Add some products to the list, they should appear in the list below.
Now try deleting some. This should work for all other items than the first, which will crash.

## Code Sample

[https://github.com/StephenBeirlaen/realm-recyclerview-deletebug](https://github.com/StephenBeirlaen/realm-recyclerview-deletebug)

## Version of Realm and Tooling

- Realm Object Server Version: 1.2.1
- Flavor:
  - [ ] Developer
  - [x] Professional
  - [ ] Enterprise
- Server OS & Version: CentOS 7 x64
- Client SDK Version: 1.2.1
- Client OS & Version: Android 6

**Comment by sushihangover** [comment]
@StephenBeirlaen I did a quick look at your `CreateListener` method:

One quick and dirty workaround to avoid the recycler pool concurrency issue is to use `NotifyDataSetChanged` only if you are deleting the first item in the `V7.Widget.Recycler`, you will *lose* the pretty slide up animation of all the cells when deleting the first row, but it will allow you to continue.

```
// For deletions, the adapter has to be notified in reverse order.
int[] deletions = changeSet.DeletedIndices;
for (int i = deletions.Length - 1; i >= 0; i--) // Todo: Improve with OrderedCollectionChangeSet like Android example - not available (yet)
{
	if (deletions[i] == 0)
		NotifyDataSetChanged();
	else
		NotifyItemRemoved(deletions[i]);
}
```

The longer answer involves handling the layout/animations/etc.. yourself to avoid all the recycler strange inconsistencies 😢 . I used the brilliant 🎉 Java-based `FlexibleAdapter` as my model when I wrote a Realm/C# Adapter as that project has dealt with all(?) issues you might need to solve (scrolling, swipes, undos, filtering, endless scrolling, etc... when dealing with the recyclers.

* https://github.com/davideas/FlexibleAdapter

**Comment by StephenBeirlaen** [comment]
@sushihangover Thank you for your reply. I had no idea that wouldn't trigger the issue. So it's actually a bug with the RecyclerView itself and not with Realm?

FlexibleAdapter looks promising, I didn't know of it before. Unfortunately it is Java based and I already had some trouble getting this conversion done... This one looks rather big. Maybe you want to share your C# implementation? :) Thanks in advance!

**Comment by sushihangover** [comment]
@StephenBeirlaen It is not *really* a bug in the `RecyclerView`, in a simple string array adapter you should/might not ever see it, but in working on a couple of Android apps w/ some ex-Google/Android devs I learned it ends up being a multifaceted *issue* that involves a number of components (ViewGroups, widgets in those groups, animation of those elements, layout hierarchy, pending UI updates of the next Looper cycle,  etc...) and then you put Realm into the mix.

There are a few Java-based SO questions involving issues exactly like this (Inconsistency detected w/ state no. XX) and there are many answers that solved it in very different ways for different scenarios.

This hack is just one that I know works in how you coded your layout, holder & adapter. Overriding the default animation and providing your own anims is another way, or placing your `NotifyItemRemoved` in a `Runnable` and delaying the delete until the next `Looper` cycle *should* work 👿  , etc.

I would love to open source my version of XtremelyWickedAdapter for Realm (one client laughed at the  project name, FlexibleRealmAdapter seems to boring...), finding people to help that are doing native UI work via C# vs. Forms only is rare, struck out in last user group I went to and while all my clients are doing native UIs I can not ask any of their employees due to my contracts, and I just have not had the time personally (I really want to do a parallel feature4feature version with *new* 5.0RC version of Flexable, maybe a client w/ 💰 will ask one day 😅 )

**Comment by StephenBeirlaen** [comment]
Thank you for your answer! You seem to be very knowledgeable on this matter. I'm now more able to accept the fact that this problem is too complex to fix myself. So I'll just stick with the workaround you provided me for now :)

This library offers more than I could ever think of. It would be an interesting project indeed :)

**Comment by nirinchev** [comment]
Thanks for helping @sushihangover! @StephenBeirlaen, following the discussion it seems that's more of a quirk with Android's RecyclerView. Should we consider the issue closed or do you have more questions/concerns?

**Comment by StephenBeirlaen** [comment]
Yes, it can be closed :) thanks all!
