### ISSUE TITLE
Realm works locally on IIS with .Net core 2.1, but when deployed to IIS server fails

### ISSUE THREAD

**Issue by yokesh8** [realm/realm-dotnet#1867]
## Goals
I am using realm, with .Net core 2.1 and it works successfully when I have deployed the application to one of the laptop by enabling IIS on the laptop. When I use the same code to deploy on IIS server it fails.

**Below is the Exception:**

An unhandled exception occurred while processing the request.

DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(get_eventloop get, post_on_event_loop post, release_eventloop release)

TypeInitializationException: The type initializer for 'Realms.Sync.SharedRealmHandleExtensions' threw an exception.

Realms.Sync.SharedRealmHandleExtensions.DoInitialFileSystemConfiguration()

DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(get_eventloop get, post_on_event_loop post, release_eventloop release)

Realms.SynchronizationContextEventLoopSignal.Install()

Realms.NativeCommon.Initialize()

Realms.Sync.SharedRealmHandleExtensions..cctor()

Show raw exception details 

System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(get_eventloop get, post_on_event_loop post, release_eventloop release)
   at Realms.SynchronizationContextEventLoopSignal.Install()
   at Realms.NativeCommon.Initialize()
   at Realms.Sync.SharedRealmHandleExtensions..cctor()

TypeInitializationException: The type initializer for 'Realms.Sync.SharedRealmHandleExtensions' threw an exception.

Realms.Sync.SharedRealmHandleExtensions.DoInitialFileSystemConfiguration()

Realms.Sync.User.LoginAsync(Credentials credentials, Uri serverUri)

WebAppCore2.Controllers.HomeController.GetInstance() in HomeController.cs

WebAppCore2.Controllers.HomeController.Index() in HomeController.cs

lambda_method(Closure , object )

Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable+Awaiter.GetResult()

Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[ ] arguments)

System.Threading.Tasks.ValueTask<TResult>.get_Result()

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)

Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)

Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details 

System.TypeInitializationException: The type initializer for 'Realms.Sync.SharedRealmHandleExtensions' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'realm-wrappers' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Realms.SynchronizationContextEventLoopSignal.install_eventloop_callbacks(get_eventloop get, post_on_event_loop post, release_eventloop release)
   at Realms.SynchronizationContextEventLoopSignal.Install()
   at Realms.NativeCommon.Initialize()
   at Realms.Sync.SharedRealmHandleExtensions..cctor()

    * End of inner exception stack trace ---
at Realms.Sync.SharedRealmHandleExtensions.DoInitialFileSystemConfiguration()
at Realms.Sync.User.LoginAsync(Credentials credentials, Uri serverUri)
at WebAppCore2.Controllers.HomeController.GetInstance() in C:\Temp\WebAppCore2\Controllers\HomeController.cs:line 59
at WebAppCore2.Controllers.HomeController.Index() in C:\Temp\WebAppCore2\Controllers\HomeController.cs:line 32
at lambda_method(Closure , Object )
at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[ ] arguments)
at System.Threading.Tasks.ValueTask`1.get_Result()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

## Actual Results
I should connect to realm when deployed to IIS server. and I am getting following issue 

## Code Sample
```
           var credentials = Credentials.UsernamePassword(UserName, Password, false);
            var authURL = new Uri(RealmURL);
            var user = await Realms.Sync.User.LoginAsync(credentials, authURL); 
          
            var serverURL = new Uri(RealmInstance, UriKind.Relative);
          
            var config = new FullSyncConfiguration(serverURL, user, LocalPath);
            realm = await Realm.GetInstanceAsync(config);
```

## Version of Realm and Tooling
I am using realm 3.4.0, installed though nugget package. visual studio vs2017, .net core 2.1 and realm object server

**Comment by nirinchev** [comment]
It looks like the problem is that the `realm-wrappers` dll is not found. When deploying your app, what platform are you targeting? Note that due to https://github.com/realm/realm-dotnet/issues/1860, you need to specify `win10-x64` rather than just `win-x64`. We hope to address that in the next release.

**Comment by yokesh8** [comment]
I have the following folders under 'Runtimes'.
1. linux-x64
2. osx.10.10-x64
3. win81-x64
4. win81-x86

So as per my understanding it works on laptop, when we deployed through IIS is because laptop operating system is **'Windows 10'.** 

But when the same code is deployed on server through IIS, it doesn't work because of the server operating system is **'Windows Server 2012R2'.** 

Seems like we need edit pubxml file. if that's correct based on above scenario can you guide us which part of section needs to be edited to get it working.

**Following the pubxml file for my project.**

<?xml version="1.0" encoding="utf-8"?>



<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ProjectGuid>******-***-****-****-***********</ProjectGuid>
    <SelfContained>false</SelfContained>
    <_IsPortable>true</_IsPortable>
    <publishUrl>C:\Project Publish\PRojectName\</publishUrl>
    <DeleteExistingFiles>True</DeleteExistingFiles>
  </PropertyGroup>
</Project>

**Comment by yokesh8** [comment]
According to this post, https://github.com/realm/realm-dotnet/issues/1345 it should work on Windows Server 2012 R2 right?

**Comment by pieperu** [comment]
I'm also experiencing this issue with a .net 4.6.1 Web Api. On this line:

`var adminUser = await User.LoginAsync(credentials, new Uri($"https://{ServerUrl}"));`

It falls over with:

`Unable to load DLL 'realm-wrappers'`

his issue has pretty much stopped progress entirely. Is there any news on when this might be fixed?

**Comment by yokesh8** [comment]
I got mine resolved.
