### ISSUE TITLE
[Bug]: The method 'Select' is not supported

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2548]
### What happened?

Try recover list using LINQ 

(from list
 in App.AppEnvironmentService.SyncDB.RealmInstance.All<FavoriteList>()
 select list.Name).ToList()

### Repro steps

(from list
 in App.AppEnvironmentService.SyncDB.RealmInstance.All<FavoriteList>()
 select list.Name).ToList()

### Version

10.3.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### What type of application is this?

Xamarin

### Host OS and version

Windows 10 

### Client OS and version

Windows 10

### Code snippets

   public class FavoriteList : RealmObject
    {
        [PrimaryKey]
        public string _id { get; set; } = Guid.NewGuid().ToString();

        [Required]
        public string _partitionKey { get; set; } /* user Id */

        [Required]
        [Indexed]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public IList<FavoritedVerbete> FavoritedVerbetes { get; }

        #region Constructor
        public FavoriteList( string partition, string name)
        {
            this._partitionKey = partition;
            this.Name = name;
        }

        public FavoriteList() { }

        #endregion

    }

### Stacktrace of the exception/crash you're getting

```shell
System.NotSupportedException
  HResult=0x80131515
  Message=The method 'Select' is not supported
  Source=Realm
  StackTrace:
   at Realms.RealmResultsVisitor.VisitMethodCall(MethodCallExpression node)
   at Realms.RealmResults`1.GetOrCreateHandle()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Realms.RealmCollectionBase`1.get_Count()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LexSemanticClient.Services.FavoriteService.GetFavoritesNameList() in C:\Users\FavoriteService.cs:line 317
   at LexSemanticClient.ViewModel.VerbeteViewModel..ctor(VerbeteCardView verbeteCard, ReturnToolBarView returnToolBar) in C:\Users\VerbeteViewModel.cs:line 154
   at LexSemanticClient.Views.Pages.VerbetePage..ctor() in C:\Users\VerbetePage.xaml.cs:line 31
```

**Comment by nirinchev** [comment]
That is correct - [Select/SelectMany are not yet supported](https://docs.mongodb.com/realm-sdks/dotnet/latest/linqsupport.html#projection-operators) and there are no immediate plans to add support.

As a workaround, you can cast the collection to `Enumerable` and use LINQ-to-object's version of select:

```csharp
var myList = App.AppEnvironmentService.SyncDB.RealmInstance.All<FavoriteList>().AsEnumerable().Select(f => f.Name).ToList();
```

The key here is the `AsEnumerable()` call that will force the `Select` to be evaluated on `IEnumerable<FavoriteList>` rather than `IQueryable<FavoriteList>`.

**Comment by carbonete** [comment]
Thanks @nirinchev
