### ISSUE TITLE
Realm.GetInstanceAsync immediately throws a System.AccessViolationException

### ISSUE THREAD

**Issue by julesx** [realm/realm-dotnet#2597]
### What happened?

Trying to open a realm database via `Realm.GetInstanceAsync` immediately throws a `System.AccessViolationException`

### Repro steps

Attempt to use `Realm.GetInstanceAsync` to open a .realm file

### Version

10.3.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

WPF

### Client OS and version

Windows 10 Build 19042.1165 Version 20H2

### Code snippets

```
private static RealmConfiguration GetConfig(string path)
        {
            return new RealmConfiguration(path)
            {
                ObjectClasses = new[] {
                    typeof(CustomObject1),
                    typeof(CustomObject2),
                    ....
                },
                SchemaVersion = SCHEMA_VERSION,
                MigrationCallback = (migration, oldSchemaVersion) =>
                {
                    //some custom migration code
                }
            };
        }

var realm = await Realm.GetInstanceAsync(GetConfig(path));
```

### Stacktrace of the exception/crash you're getting

```shell
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Realms.SharedRealmHandle.NativeMethods.open(Configuration configuration, SchemaObject[] objects, Int32 objects_length, SchemaProperty[] properties, Byte[] encryptionKey, NativeException& ex)
   at Realms.SharedRealmHandle.Open(Configuration configuration, RealmSchema schema, Byte[] encryptionKey) in C:\jenkins\workspace\realm_realm-dotnet_PR-2497\Realm\Realm\Handles\SharedRealmHandle.cs:line 234
   at Realms.RealmConfiguration.CreateRealm(RealmSchema schema) in C:\jenkins\workspace\realm_realm-dotnet_PR-2497\Realm\Realm\Configurations\RealmConfiguration.cs:line 148
   at Realms.RealmConfiguration.<>c__DisplayClass25_0.<CreateRealmAsync>b__0() in C:\jenkins\workspace\realm_realm-dotnet_PR-2497\Realm\Realm\Configurations\RealmConfiguration.cs:line 177
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### Build environment

Microsoft Visual Studio Community 2022 Preview (64-bit)

**Comment by nirinchev** [comment]
Hm... looks like something translated to native is getting read incorrectly. Does this happen consistently and can you provide a sample project that reproduces the issue? That would help us immensely.

**Comment by julesx** [comment]
it happens consistently.
i had an existing project using a previous SDK version, it worked fine.
I updated nuget packages, no other changes, error on loading existing database.
create new database, same issue.
will try and provide a sample.

**Comment by nirinchev** [comment]
That's super valuable, thank you. Do you remember which version you used before that? Was it 10.2.1?

**Comment by julesx** [comment]
sorry that i do not know
