### ISSUE TITLE
Hot reload does not work with Realm 10.19.0 and .NET MAUI Blazor App .NET 6

### ISSUE THREAD

**Issue by syntax-art** [realm/realm-dotnet#3213]
### What happened?

When you use Realm 10.19.0 in a  .NET MAUI Blazor App .NET 6 and then use Hot Reload this will not work and the application will ask you to stop and edit.  

I've also tested this with a brand new project with only Realm added and then created an instance of the database and written an object to a collection.

Error Message
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7038	Failed to emit module 'MauiApp2': Changing the version of an assembly reference is not allowed during debugging: 'System.Linq.Queryable, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' changed version to '6.0.0.0'.	MauiApp2 (net6.0-android)		1	Active

This maybe because of the Remotion.Linq dependency which has been added to Realm.  

### Repro steps

- Create a new project with .NET MAUI Blazor App .NET 6
- Add Realm 10.19.0
- Go to the Counter page and in the IncrementCount() write some code to add objects to a collection.
- Run the application
- Test the button to add an item to the database
- Add some text to the HTML on any page
- Whilst the app is running click Hot Reload

You will see that Hot Reload does not work and Visual Studio will ask you to edit or stop the app.

### Version

.NET 6.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

Windows 10, .NET MAUI Blazor application

### Stacktrace of the exception/crash you're getting

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7038	Failed to emit module 'MauiApp2': Changing the version of an assembly reference is not allowed during debugging: 'System.Linq.Queryable, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' changed version to '6.0.0.0'.	MauiApp2 (net6.0-android)		1	Active
```

**Comment by nirinchev** [comment]
Hey, thanks for the report. Has this ever worked with a different Realm version? I'm asking because last we were looking at this, hot reload wasn't supported for libraries with native modules. This may have changed with a recent MAUI update, so if you were ever able to get it to work with a different Realm version, that would point to a recent change that is the culprit.

**Comment by syntax-art** [comment]
Hey thank you for your reply.

I've tested some the other versions and **10.5.0** is working

I've tested **10.5.1** and version above this and they don't work with Hot Reload.

**Comment by syntax-art** [comment]
Another Update

When running version 10.5.0 on Android the following exception is thrown when using Realm.GetInstance()

{System.TypeInitializationException: The type initializer for 'Realms.SharedRealmHandle' threw an exception.
 ---> System.DllNotFoundException: realm-wrappers
   at Realms.SynchronizationContextScheduler.Install() in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Native\SynchronizationContextScheduler.cs:line 146
   at Realms.NativeCommon.Initialize() in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Native\NativeCommon.cs:line 57
   at Realms.SharedRealmHandle..cctor() in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Handles\SharedRealmHandle.cs:line 190
   --- End of inner exception stack trace ---
   at Realms.RealmConfiguration.CreateRealm(RealmSchema schema) in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Configurations\RealmConfiguration.cs:line 147
   at Realms.Realm.GetInstance(RealmConfigurationBase config, RealmSchema schema) in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Realm.cs:line 120
   at Realms.Realm.GetInstance(RealmConfigurationBase config) in D:\a\realm-dotnet\realm-dotnet\Realm\Realm\Realm.cs:line

**Comment by nirinchev** [comment]
Not sure I follow - didn't you say hot reload works with Realm 10.5.0? Did it work on a non-android platform or?

**Comment by syntax-art** [comment]
My apologies if this isn't clear.

Version 10.5.0 works on Windows Machine and with Hot Reload.
Version 10.5.0 does not work when you are using the Android Emulator the exception is thrown above.

Version 10.19.0 works on Windows Machine and Android Emulator.
Version 10.19.0 does not work with Hot Reload when using Windows Machine or Android Emulator.

Is there a fix for 10.19.0 so that it works with Hot Reload?

**Comment by nirinchev** [comment]
Thanks, that clarifies things.

10.5.0 should work on Android - my guess is that when switching versions, some artifacts were not correctly cleaned up/replaced by NuGet, so my suggestion would be to try removing the bin/obj folders and possibly uninstalling the app from the device.

For 10.19.0, we don't have a fix yet - we haven't investigated it yet.

**Comment by nirinchev** [comment]
Ok, the issue appears to be that certain assemblies are being loaded dynamically after the Realm weaver has processed the assembly once. Still not exactly clear what we can do to handle this out of the box, but a workaround you can apply is to add the following to your `MauiProgram`:

```csharp
        _ = Enumerable.Range(0, 1).Where(c => c > 0).ToList().AsQueryable().FirstOrDefault();
```

Basically what it does is force reference `System.Linq`, `System.Collections`, and `System.Linq.Expressions` so that even the first build references version 6.0.0 of these assemblies.

**Comment by syntax-art** [comment]
Hey that's worked nicely, thank you for your help.  It's much appreciated :)
