### ISSUE TITLE
Realm does not start on Android 14

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#3458]
### What happened?

Passing on a report from our users:

```
2023-10-05 11:59:42 [error]: Realms.Exceptions.RealmException: flock() failed: Function not implemented (38)
2023-10-05 11:59:42 [error]: at Realms.NativeException.ThrowIfNecessary()
2023-10-05 11:59:42 [error]: at Realms.SharedRealmHandle.Open(Configuration configuration)
2023-10-05 11:59:42 [error]: at Realms.RealmConfiguration.CreateHandle(Configuration& configuration)
2023-10-05 11:59:42 [error]: at Realms.RealmConfigurationBase.CreateRealm()
2023-10-05 11:59:42 [error]: at Realms.Realm.GetInstance(RealmConfigurationBase config)
2023-10-05 11:59:42 [error]: at osu.Game.Database.RealmAccess.getRealmInstance()
2023-10-05 11:59:42 [error]: at osu.Game.Database.RealmAccess.prepareFirstRealmAccess()
```

### Repro steps

N/A

### Version

11.5.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Console/Server

### Client OS and version

Environment: Android (Unix 34.0.0.0), 8 cores

**Comment by papafe** [comment]
Hi @peppy, thanks for the report, we'll take a look

**Comment by nirinchev** [comment]
I filed https://github.com/realm/realm-core/issues/7037 to track this since it's not an issue with the .NET SDK itself.

**Comment by peppy** [comment]
Thanks. Wasn't sure which end has responsibility in this case 😅 .

**Comment by nirinchev** [comment]
No worries - as long as it's reported, we'll figure out who's to blame 😝

**Comment by tn7111** [comment]
Hello! A lot of crashes from users in our project with this exception. Any news on this? Thanks in advance :)

**Comment by nirinchev** [comment]
Per my comment, this issue was transferred to https://github.com/realm/realm-core/issues/7037 and the last comment there was that it was resolved upstream. If you have more details to add, please do so in the realm-core issue.

**Comment by tn7111** [comment]
Oh, sorry for bothering, thank you!
