### ISSUE TITLE
Build failed if the project is located under the path which contains Japanese(muti-byte) character

### ISSUE THREAD

**Issue by zaki50** [realm/realm-dotnet#540]
IDE: Visual Studio 2015
Realm version: 0.74.1
OS: Windows 10

I got following error message when I imported Realm into Xamarin project.

This project is located in `C:\Users\zaki\OneDrive\ドキュメント\Visual Studio 2015\Projects\`, and this is the default location of Japanese locale.

As you can see, `ドキュメント` is not handled correctly.

```
重大度レベル  コード   説明  プロジェクト  ファイル    行 抑制状態
エラー       "ConvertResourcesCases" タスクが予期せずに失敗しました。
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\zaki\OneDrive\繝峨く繝･繝｡繝ｳ繝・Visual Studio 2015\Projects\MyRealm2\MyRealm2\obj\Debug\__library_projects__\Realm\library_project_imports\res'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, SearchOption searchOption)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(ITaskItem item, Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources(Dictionary`2 acwMap)
   at Xamarin.Android.Tasks.ConvertResourcesCases.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

When I move this project to `C:\Users\zaki\visual studio 2015\Projects`, it works.

**Comment by AndyDentFree** [comment]
Have you built other Xamarin projects successfully with this path, with your **current Xamarin setup**?

Looking at that stack, it seems to be an error in part of the Xamarin tooling `Xamarin.Android.Tasks.ConvertResourcesCases.FixupResources` and I can't think of anything we're doing which involves that. 

I will get our Japanese support guys to try this out if you can please give us a bit more information:

1. You're using VS2015 - is this with Update 1 or Update 2 installed? (Version number visible in the Help - About Microsoft Visual Studio menu option)
2. Which Xamarin channel are you on? (Tools - Options, scroll down to Xamarin and twist open to check the Other category).

**Comment by zaki50** [comment]
Visual Studio Community 2015 Version 14.0.25123.00 Update 2

Stable chnannel

**Comment by AndyDentFree** [comment]
This [thread on the Xamarin Forums](https://forums.xamarin.com/discussion/comment/184384/#Comment_184384) seems to confirm it is a Xamarin problem  _Yes it's caused by any non English character in the root folder._

Please try a different root folder under OneDrive, I suggest simply adding a `test` root and see if your Japanese characters work below that root.
