### ISSUE TITLE
Migration needed even for adding simple column

### ISSUE THREAD

**Issue by Rohitwagh** [realm/realm-dotnet#749]
**After adding a simple column to the realm object,  if fails with "RealmMigrationNeededException".**

> **Steps to reproduce**: 

1. Release build and install app with some basic class (of RealmObject)
2. add a simple property to the class.
3. Update the app on top of previously installed app.
4. the app breaks when it find that a new property has been added.

#### Expected Results

As per the documentation, 

> Realm will automatically perform migrations that can be done without processing, like adding and removing classes or adding and removing properties from a class. 

#### Actual Results

 It throws an exception:

> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.reflect.InvocationTargetException
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
Caused by: android.runtime.JavaProxyThrowable: Realms.RealmException: Migration is required due to the following errors:
                                                   - Property 'ServerIdDuplicate' has been added to latest object model.
 at Realms.NativeException.ThrowIfNecessary () <0x9f91d838 + 0x00028> in <filename unknown>:0 
 at Realms.SharedRealmHandle.Open (Realms.SchemaHandle schemaHandle, System.String path, Boolean readOnly, Boolean durability, System.Byte[] encryptionKey, UInt64 schemaVersion) <0x9f9209b8 + 0x000bf> in <filename unknown>:0 
 at Realms.Realm.GetInstance (Realms.RealmConfiguration config, Realms.RealmSchema schema) <0x9f915eb0 + 0x001af> in <filename unknown>:0 
 at Realms.Realm.GetInstance (Realms.RealmConfiguration config) <0x9f915c08 + 0x00017> in <filename unknown>:0 

#### Version of Realm and tooling
Realm version(s): 0.77.1

Xamarin/Visual Studio version: VS2015, 

Which operating system version and device: MOTO E2, Android 5.1, API 22

**Comment by AndyDentFree** [comment]
Hi @Rohitwagh sorry but the documentation needs a bit of enhancing. You need to set a new [SchemaVersion](https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm_configuration.html#a85df4a7b677d5f4c23ec55f4ed982d7e) on your [RealmConfiguration](https://realm.io/docs/xamarin/latest/api/class_realms_1_1_realm_configuration.html) in order for migrations to be automatic.

That protects you and your app users against unintentional schema changes.

I posted a comprehensive example [on this issue](https://github.com/realm/realm-dotnet/issues/669#issuecomment-233036446)
