### ISSUE TITLE
Crash adding nested objects with backlinks

### ISSUE THREAD

**Issue by AndyDentFree** [realm/realm-dotnet#997]
Crash as documented below.

user description

Child objects are already managed but parent not.

Having a RealmClassA, RealmClassB, both with a IList of the same RealmClassC instances

It's getting complicated, but Class C have a list of ClassD, and each ClassD have a back reference (foreign key in conventional DB) to Class C

seems, when I removed the back-entry, it worked

```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid]   at Taskr.Core.Persistance.RealmParcel+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x00086] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Realms.Realm.Manage[T] (T obj, System.Boolean update) [0x00000] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Taskr.Core.Persistance.RealmEvent+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x0006b] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Realms.Realm.Manage[T] (T obj, System.Boolean update) [0x00000] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Taskr.Core.Persistance.RealmEventQueueItem+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x00035] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Realms.Realm.Manage[T] (T obj, System.Boolean update) [0x00000] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at Taskr.Core.EventQueueStore+<Save>c__async0+<Save>c__AnonStorey1.<>m__0 (Realms.Realm realmObject) [0x0001c] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid]   at Realms.Realm+<WriteAsync>c__AnonStorey0.<>m__0 () [0x00013] in <5ae90944369346da8059fc382051fc68>:0 
[MonoDroid]   at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Threading.Tasks.Task.Execute () [0x00016] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at Taskr.Core.EventQueueStore+<Save>c__async0.MoveNext () [0x000bb] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at Taskr.Core.EventCore.EventModel+<Loaded>c__async0.MoveNext () [0x0008c] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at Taskr.Core.Loading.Scan.LoadingScanModel+<Loaded>c__async0.MoveNext () [0x00071] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at Taskr.Core.Loading.Scan.LoadingScanViewModel+<OnFinish>c__async3.MoveNext () [0x00076] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext () [0x0013a] in <69bce0378e8e413982d3b552d7e387a8>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext () [0x00088] in <69bce0378e8e413982d3b552d7e387a8>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at MvvmCross.Core.ViewModels.MvxAsyncCommandBase+<Execute>d__14.MoveNext () [0x00073] in <69bce0378e8e413982d3b552d7e387a8>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <3dc9ed3d31194319991e686734adcb10>:0 
[MonoDroid]   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <23a8d9bf141f4ef5b5a764e32add1f40>:0 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <23a8d9bf141f4ef5b5a764e32add1f40>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <23a8d9bf141f4ef5b5a764e32add1f40>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object:679fef96-c2ff-4341-8a69-2f68d7cf27bb (intptr,intptr)
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_throw'.
[Mono] Probing 'java_interop_jnienv_throw'.
[Mono] Found as 'java_interop_jnienv_throw'.
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
[AndroidRuntime] 	at dalvik.system.NativeStart.main(Native Method)
[AndroidRuntime] Caused by: java.lang.reflect.InvocationTargetException
[AndroidRuntime] 	at java.lang.reflect.Method.invokeNative(Native Method)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Method.java:511)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
[AndroidRuntime] 	... 2 more
[AndroidRuntime] Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[AndroidRuntime]   at Taskr.Core.Persistance.RealmParcel+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x00086] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[AndroidRuntime]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc382051fc68>:0 
[AndroidRuntime]   at Realms.Realm.Manage[T] (T obj, System.Boolean update) [0x00000] in <5ae90944369346da8059fc382051fc68>:0 
[AndroidRuntime]   at Taskr.Core.Persistance.RealmEvent+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x0006b] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[AndroidRuntime]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc382051fc68>:0 
[AndroidRuntime]   at Realms.Realm.Manage[T] (T obj, System.Boolean update) [0x00000] in <5ae90944369346da8059fc382051fc68>:0 
[AndroidRuntime]   at Taskr.Core.Persistance.RealmEventQueueItem+RealmHelper.CopyToRealm (Realms.RealmObject instance, System.Boolean update) [0x00035] in <62e8b4b02e2f4164823cc226e815cf34>:0 
[AndroidRuntime]   at Realms.Realm.ManageInternal (Realms.RealmObject obj, System.Type objectType, System.Boolean update) [0x0012b] in <5ae90944369346da8059fc38...
```

**Comment by nirinchev** [comment]
Is the back reference an object or not? It seems like it should be supported, but there might be a bug in our copy implementation. Can you try to create a unit test that replicates the crash scenario?

**Comment by nirinchev** [comment]
@AndyDentFree can you check if https://github.com/realm/realm-dotnet/pull/1040 fixes this?

**Comment by nirinchev** [comment]
I'm closing this. Feel free to reopen if you manage to reproduce it with the latest sources.
